// data.ts
export const categories = [
  { id: 'all', label: 'Khóa học học' },
  { id: 'graphic', label: 'Graphic Design' },
  { id: 'web', label: 'Web Design' },
  { id: 'content', label: 'Content Writing' },
  { id: 'marketing', label: 'Digital Marketing' },
  { id: 'business', label: 'Business' },
  { id: 'finance', label: 'Finance' },

];

export const courses = [
  {
    id: "graphic",
    slug: "khoa-hoc-online-thiet-ke-graphic-co-ban",
    title: "Khóa học online thiết kế Graphic cơ bản",
    image: "/assets/v.webp",
    originalPrice: 6000000,
    discountedPrice: 4000000,
    discount: 33,
    category: "graphic",
    instructor: {
      name: "Đoàn Hương Giang",
      avatar: "/assets/e.webp",
      bio: [
        "Khởi đầu từ 2 bàn tay trắng và gầy gò, năm 1988, ba bán hàng tạp hóa ở chợ, còn mẹ tui xoay sở tự học cắt may ở nhà, khi tiệm may có chút uy tín, mẹ mở thêm lớp dạy cắt may. Một đứa bé gái 8 tuổi là tui năm ấy, quan sát mẹ làm suốt rồi cũng chấp chới chân đạp máy may được 1 chiếc áo 3 lỗ cho đứa em.",
      ],
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "web",
    slug: "khoa-hoc-online-thiet-ke-web-co-ban",
    title: "Khóa học online thiết kế Web cơ bản",
    image: "/assets/watchs.webp",
    originalPrice: 6000000,
    discountedPrice: 4000000,
    discount: 33,
    category: "web",
    instructor: {
      name: "Dương Phi Hùng",
      avatar: "/assets/watchs.webp",
      bio: [
        "Dương Phi Hùng là một chuyên gia thiết kế web giàu kinh nghiệm, chuyên tập trung vào giao diện người dùng (UI/UX).",
        "Anh đã tư vấn và triển khai thành công hàng trăm dự án cho các doanh nghiệp nhỏ và vừa tại Việt Nam."
      ],
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "content",
    slug: "khoa-hoc-online-thiet-ke-content-co-ban",
    title: "Khóa học online thiết kế content cơ bản",
    image: "/assets/v.webp",
    originalPrice: 6000000,
    discountedPrice: 4000000,
    discount: 34,
    category: "content",
    instructor: {
      name: "Vũ Trọng Công",
      avatar: "/assets/e.webp",
      bio: [
        "Vũ Trọng Công là CEO của MewTheme – một trong những công ty hàng đầu tại Việt Nam chuyên về thiết kế UI/UX và triển khai website trên nền tảng Sapo, Shopify, và nhiều nền tảng khác.",
        "Trong suốt thời gian làm việc tại MewTheme, anh đã giúp nhiều khách hàng cải thiện hiệu suất website và tối ưu hóa trải nghiệm người dùng.",
        "Với hơn 6 năm kinh nghiệm, anh được đánh giá là một trong những chuyên gia hàng đầu trong ngành."
      ],
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "marketing",
    slug: "khoa-hoc-online-thiet-ke-marketing-co-ban",
    title: "Khóa học online thiết kế marketing cơ bản",
    image: "/assets/u.webp",
    originalPrice: 6000000,
    discountedPrice: 4000000,
    discount: 33,
    category: "marketing",
    instructor: {
      name: "Nguyễn Hà Trang",
      avatar: "/assets/u.webp",
      bio: [
        "Nguyễn Hà Trang là chuyên gia tiếp thị số (Digital Marketing) với hơn 8 năm kinh nghiệm.",
        "Chị đã đào tạo hàng trăm học viên thành công và giúp nhiều doanh nghiệp tăng trưởng mạnh mẽ thông qua chiến lược marketing sáng tạo."
      ],
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "content",
    slug: "khoa-hoc-online-thiet-ke-content-co-ban",
    title: "Khóa học online thiết kế content cơ bản",
    image: "/assets/v.webp",
    originalPrice: 6000000,
    discountedPrice: 4000000,
    discount: 34,
    category: "content",
    instructor: {
      name: "Vũ Trọng Công",
      avatar: "/assets/e.webp",
      bio: "Thông tin về Vũ Trọng Công sẽ sớm được cập nhật.",
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "graphic-advanced",
    slug: "khoa-hoc-online-thiet-ke-graphic-nang-cao",
    title: "Khóa học online thiết kế Graphic nâng cao",
    image: "/assets/v.webp",
    originalPrice: 8000000,
    discountedPrice: 6000000,
    discount: 25,
    category: "graphic",
    instructor: {
      name: "Đoàn Hương Giang",
      avatar: "/assets/e.webp",
      bio: "Khởi đầu từ 2 bàn tay trắng...",
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "web-advanced",
    slug: "khoa-hoc-online-thiet-ke-web-nang-cao",
    title: "Khóa học online thiết kế Web nâng cao",
    image: "/assets/v.webp",
    originalPrice: 8000000,
    discountedPrice: 6000000,
    discount: 25,
    category: "web",
    instructor: {
      name: "Dương Phi Hùng",
      avatar: "/assets/e.webp",
      bio: "Thông tin về Ngô Đức Hiếu sẽ sớm được cập nhật.",
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "business-advanced",
    slug: "khoa-hoc-online-thiet-ke-business-nang-cao",
    title: "Khóa học online thiết kế business nâng cao",
    image: "/assets/v.webp",
    originalPrice: 8000000,
    discountedPrice: 6000000,
    discount: 25,
    category: "business",
    instructor: {
      name: "Ngô Đức Hiếu",
      avatar: "/assets/e.webp",
      bio: "Thông tin về Ngô Đức Hiếu sẽ sớm được cập nhật.",
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "marketing-advanced",
    slug: "khoa-hoc-online-thiet-ke-marketing-nang-cao",
    title: "Khóa học online thiết kế marketing nâng cao",
    image: "/assets/v.webp",
    originalPrice: 8000000,
    discountedPrice: 6000000,
    discount: 25,
    category: "marketing",
    instructor: {
      name: "Nguyễn Hà Trang",
      avatar: "/assets/e.webp",
      bio: "Thông tin về Ngô Đức Hiếu sẽ sớm được cập nhật.",
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "content-advanced",
    slug: "khoa-hoc-online-thiet-ke-content-nang-cao",
    title: "Khóa học online thiết kế content nâng cao",
    image: "/assets/v.webp",
    originalPrice: 8000000,
    discountedPrice: 6000000,
    discount: 25,
    category: "content",
    instructor: {
      name: "Vũ Trọng Công",
      avatar: "/assets/e.webp",
      bio:  [
        "Vũ Trọng Công là CEO của MewTheme – một trong những công ty hàng đầu tại Việt Nam chuyên về thiết kế UI/UX và triển khai website trên nền tảng Sapo, Shopify, và nhiều nền tảng khác. Với hơn 6 năm kinh nghiệm trong lĩnh vực sản xuất theme website, customer service, hỗ trợ SEO web, tối ưu pagespeed website core vitas, ông đã đóng góp rất nhiều cho sự phát triển của ngành thiết kế web tại Việt Nam.",
        "Trong suốt thời gian làm việc tại MewTheme, Vũ Trọng Công đã xây dựng và phát triển nhiều sản phẩm website đẹp mắt, chuyên nghiệp và tối ưu hiệu suất. Với kinh nghiệm và kỹ năng của mình, anh đã giúp đỡ nhiều khách hàng triển khai website theo những yêu cầu đặc biệt, từ thiết kế đến phát triển, tối ưu hóa SEO và quảng bá thương hiệu.",
        "Ngoài ra, Vũ Trọng Công cũng là một chuyên gia trong việc tối ưu pagespeed website core vitas. Với khả năng tối ưu hoá hiệu suất của website, anh đã giúp cho nhiều khách hàng của MewTheme cải thiện tốc độ tải trang web và tăng trải nghiệm người dùng."
      ],
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "graphic-masterclass",
    slug: "khoa-hoc-online-thiet-ke-graphic-masterclass",
    title: "Khóa học online thiết kế Graphic Masterclass",
    image: "/assets/v.webp",
    originalPrice: 10000000,
    discountedPrice: 8000000,
    discount: 20,
    category: "graphic",
    instructor: {
      name: "Đoàn Hương Giang",
      avatar: "/assets/e.webp",
      bio: "Khởi đầu từ 2 bàn tay trắng...",
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "web-masterclass",
    slug: "khoa-hoc-online-thiet-ke-web-masterclass",
    title: "Khóa học online thiết kế Web Masterclass",
    image: "/assets/v.webp",
    originalPrice: 10000000,
    discountedPrice: 8000000,
    discount: 20,
    category: "web",
    instructor: {
      name: "Dương Phi Hùng",
      avatar: "/assets/e.webp",
      bio: "Thông tin về Ngô Đức Hiếu sẽ sớm được cập nhật.",
      bgColor: "bg-gray-900",
    },
  },
  {
    id: "business-masterclass",
    slug: "khoa-hoc-online-thiet-ke-business-masterclass",
    title: "Khóa học online thiết kế Business Masterclass",
    image: "/assets/v.webp",
    originalPrice: 10000000,
    discountedPrice: 8000000,
    discount: 20,
    category: "finance",
    instructor: {
      name: "Ngô Đức Hiếu",
      avatar: "/assets/e.webp",
      bio: "Thông tin về Ngô Đức Hiếu sẽ sớm được cập nhật.",
      bgColor: "bg-gray-900",
    },
  },
];

